#ifdef __MMI_GAME_TETRIS__
    #define TETRIS_IMG_PATH CUST_IMG_BASE_PATH"\\\\GameImages\\\\Tetris\\\\"

    <STRING id="STR_GX_TETRIS_GAME_NAME"/>
    <STRING id="STR_GX_TETRIS_HELP_DESCRIPTION"/>
    <STRING id="STR_GX_TETRIS_GRID"/>
    <STRING id="STR_GX_TETRIS_EASY"/>
    <STRING id="STR_GX_TETRIS_NORMAL"/>
    <STRING id="STR_GX_TETRIS_HARD"/>
    <STRING id="STR_GX_TETRIS_REPORT_SCORE"/>
    <STRING id="STR_GX_TETRIS_REPORT_RECORD"/>
    <STRING id="STR_GX_TETRIS_PASS"/>
    <STRING id="STR_GX_TETRIS_PASS_LAST"/>
    <STRING id="STR_GX_TETRIS_HERO_LEVEL"/>
    <STRING id="STR_GX_TETRIS_HERO_SCORE"/>
	
	<IMAGE id="IMG_ID_GX_TETRIS_SPLASH">TETRIS_IMG_PATH"TetrisSplash1"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_0">TETRIS_IMG_PATH"digit0"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_1">TETRIS_IMG_PATH"digit1"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_2">TETRIS_IMG_PATH"digit2"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_3">TETRIS_IMG_PATH"digit3"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_4">TETRIS_IMG_PATH"digit4"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_5">TETRIS_IMG_PATH"digit5"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_6">TETRIS_IMG_PATH"digit6"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_7">TETRIS_IMG_PATH"digit7"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_8">TETRIS_IMG_PATH"digit8"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_9">TETRIS_IMG_PATH"digit9"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_DIGIT_9">TETRIS_IMG_PATH"digit9"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_SCORE">TETRIS_IMG_PATH"TetrisScore"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_START">TETRIS_IMG_PATH"TetrisStart"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_LEVEL">TETRIS_IMG_PATH"TetrisLevel"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_SCORE">TETRIS_IMG_PATH"TetrisScore"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_HELP">TETRIS_IMG_PATH"TetrisHelp"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_CONTINUE">TETRIS_IMG_PATH"TetrisContinue"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_SOUND">TETRIS_IMG_PATH"TetrisSound"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_GRID">TETRIS_IMG_PATH"TetrisGrid"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_GAMESPEED_EN">TETRIS_IMG_PATH"speeden"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_GAMESCORE_EN">TETRIS_IMG_PATH"scoreen"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_GAMEPAUSE_EN">TETRIS_IMG_PATH"pauseden"GX_IMG_TYPE</IMAGE>
#ifdef    __MMI_GAME_MULTI_LANGUAGE_SUPPORT__
    <IMAGE id="IMG_ID_GX_TETRIS_GAMESPEED_CN">TETRIS_IMG_PATH"speedcn"GX_IMG_TYPE</IMAGE>
    <IMAGE id="IMG_ID_GX_TETRIS_GAMESCORE_CN">TETRIS_IMG_PATH"scorecn"GX_IMG_TYPE</IMAGE>
	<IMAGE id="IMG_ID_GX_TETRIS_GAMEPAUSE_CN">TETRIS_IMG_PATH"pausedcn"GX_IMG_TYPE</IMAGE>
#endif /*__MMI_GAME_MULTI_LANGUAGE_SUPPORT__*/

    /* Tetris NVRAM */
	<CACHEDATA type="byte" id="NVRAM_GAME_TETRIS_LEVEL" restore_flag="TRUE">
        <DEFAULT_VALUE> [0X01] </DEFAULT_VALUE>
        <DESCRIPTION> Byte Cache </DESCRIPTION>
    </CACHEDATA>
	
    <CACHEDATA type="short" id="NVRAM_GX_TETRIS_SCORE_EASY" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00, 0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Short Cache </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="short" id="NVRAM_GX_TETRIS_SCORE_MEDIUM" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00, 0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Short Cache </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="short" id="NVRAM_GX_TETRIS_SCORE_HARD" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00, 0x00] </DEFAULT_VALUE>
        <DESCRIPTION> Short Cache </DESCRIPTION>
    </CACHEDATA>
#endif  //__MMI_GAME_TETRIS__